In [16]:
import numpy as np
a = np.array([0.9, 0.9, 0.9 ])
print(np.ones(6).shape)

data = a.reshape((1, ) + a.shape)
print(data.shape)

(6,)
(1, 3)


In [8]:
print((-1, )+ (6, ) )

(-1, 6)


In [3]:
a = np.array([0.9, 0.9 ])
actions = np.array([10, 20])
print(a*actions.max(dim=1))

NameError: name 'np' is not defined

In [6]:
print(f"madezhishiang {a}, pingweismbuneg{a.shape}")

madezhishiang [0.9 0.9], pingweismbuneg(2,)


In [18]:
aa = 34523.32425
print(f'floating point formatted: {aa:2.4f}', end='*')
print('\n')
print("Art: %10d, Price per Unit:%8.2f" %(444, 543.6254), end='*')

floating point formatted: 34523.3242*

Art:        444, Price per Unit: 543.63*

In [7]:
import torch
x = torch.tensor([1.4, 6.8], requires_grad=True)
a = torch.tensor([0.4, 0.6], requires_grad=True)

F = a*x 
F.backward(gradient=torch.ones_like(F))  
# 代表F是个tensor,我要对一个多维方程进行求导,指定我的y的维度
F_scale = torch.multiply(a, x)


print(f"打印对a的导数: {a.grad}")
# 结果就是[1.4, 6.8] 但是实际上是 [ dF/da1 = (dF1/da1 + dF2/da1), dF/da2 = (dF1/da2 + dF2/da2)
print(F_scale)
loss = torch.nn.functional.mse_loss(x, a)  # 因为是mse, 所以就是一个标量
print(loss)


打印对a的导数: tensor([1.4000, 6.8000])
tensor([0.5600, 4.0800], grad_fn=<MulBackward0>)
tensor(19.7200, grad_fn=<MseLossBackward0>)


In [17]:
r = torch.randn([3,], requires_grad=True)  # 代表其他值对这个值的导数要被保留
x = torch.tensor([1., 2., 3.], requires_grad=True)
t = torch.tensor([11., 11., 11.], requires_grad=True)
F = r*x + t*x  # 三维向量
F.backward(gradient=torch.ones_like(F))   # backward代表这个F就是最终的loss, 从这个loss开始向后生成computational graphic, 一直计算到requires_grad的参数上.

print(r.grad)
print(x.grad) 

tensor([1., 2., 3.])
tensor([10.9222, 12.1767,  9.8881])


In [11]:
import torch
mean = torch.arange(10., 20., requires_grad=True)
var = torch.arange(0., 1., 0.1 , requires_grad=True)
# values = torch.normal(mean, var)
def normal_pdf(x, mean, var):
    pdf = 1 / torch.sqrt(2 * torch.pi * var) * torch.exp(-1/2 * (x - mean)**2 / var)
    return pdf
pi = normal_pdf(torch.randn(10, 1), mean, var)
print(pi.prod(dim=1))
# values.backward(gradient=torch.ones_like(values))
# print(mean.grad)
# print(var.grad)

tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       grad_fn=<ProdBackward1>)


In [14]:
mean = torch.tensor([2.54, 1.23])
var = torch.tensor([0.35, 3.02])
def normal_pdf(x, mean, var):
    pdf = 1 / torch.sqrt(2 * torch.pi * var) * torch.exp(-1/2 * (x - mean)**2 / var)
    return pdf

pi = normal_pdf(torch.tensor([1.2, 3.8]), mean, var)
print(pi)



tensor([0.0519, 0.0769])


In [23]:
ran = np.random.rand(32,32,3)
print(ran[0][0])
ran2 = np.random.rand(3, 32, 32)
print(ran2[:, 31, 31])


[0.60242776 0.32515096 0.47935122]
[0.50994032 0.56574342 0.51175941]


In [24]:
ran = np.random.rand(32,32,3)
fl = ran.flatten()
print(fl.shape)

(3072,)


In [31]:
a = torch.tensor([1, 2, 3, 4, 5])
ra = reversed(a)
print(ra)
print(a)

tensor([5, 4, 3, 2, 1])
tensor([1, 2, 3, 4, 5])


In [29]:
g = [1, 2, 3, 4, 5]
new = g[::-1]
print(new)
print(g)

[5, 4, 3, 2, 1]
[1, 2, 3, 4, 5]


In [13]:
import torch
ran = torch.randn([32, 3])

max_value, idx = torch.max(ran, 0)
print(max_value)
print(idx)
print(ran.prod(dim=1).shape)

tensor([1.9921, 2.2195, 2.2799])
tensor([14, 20,  0])
torch.Size([32])


In [2]:
import torch
ran = torch.randn([32, 3])
print(ran[-5, :])

tensor([-1.7179,  1.1552,  0.9148])


In [8]:
import numpy as np
data = np.random.rand(30)
a = np.arange(1, 10)
print(data)
b = np.concatenate((a, 10*np.ones(len(data))))
print(b)
window = np.ones(10)
conv = np.convolve(data, window)
print(conv)
print(len(conv))
aver = ()


[0.62364731 0.84380145 0.50587014 0.76244436 0.1352496  0.87651682
 0.43154771 0.92874369 0.39175602 0.28556573 0.49369412 0.75711439
 0.4661189  0.44004966 0.20991058 0.47331461 0.82734871 0.79490144
 0.92522409 0.93598127 0.37985684 0.57786455 0.63323554 0.58366508
 0.7903714  0.11299579 0.75304504 0.67871017 0.12256106 0.52259807]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10.]
[0.62364731 1.46744876 1.9733189  2.73576326 2.87101286 3.74752968
 4.17907739 5.10782108 5.4995771  5.78514283 5.65518964 5.56850258
 5.52875134 5.20635664 5.28101762 4.87781541 5.27361641 5.13977416
 5.67324223 6.32365777 6.20982049 6.03057065 6.19768729 6.34130271
 6.92176353 6.56144471 6.48714104 6.37094977 5.56828673 5.15490354
 4.7750467  4.19718215 3.56394661 2.98028153 2.18991013 2.07691434
 1.3238693  0.64515913 0.52259807]
39


In [13]:
import numpy as np
data = np.random.rand(30)
a = np.arange(1, 10)
print(data)
b = np.concatenate((a, 10*np.ones(len(data))))
print(b)
window = np.ones(10)
conv = np.convolve(data, window)
print(conv)
print(len(conv))
aver = (conv / b)[:-(10-1)]
print(aver)
print(len(aver))
print(aver[-1])

[0.91482936 0.65017162 0.79848609 0.65373296 0.11197057 0.16105479
 0.24688579 0.9214287  0.28314188 0.593564   0.64941961 0.55273612
 0.89606114 0.84707618 0.80773845 0.60816189 0.44668289 0.60600468
 0.47958686 0.32083357 0.49065491 0.45264245 0.24836827 0.2381627
 0.61107661 0.64349794 0.29795342 0.62931117 0.10673032 0.38531584]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10.]
[0.91482936 1.56500099 2.36348708 3.01722004 3.1291906  3.29024539
 3.53713118 4.45855988 4.74170176 5.33526576 5.069856   4.9724205
 5.06999555 5.26333877 5.95910665 6.40621376 6.60601086 6.29058684
 6.48703182 6.2143014  6.0555367  5.95544302 5.30775015 4.69883667
 4.50217483 4.53751087 4.3887814  4.41208789 4.03923135 4.10371362
 3.61305872 3.16041627 2.912048   2.6738853  2.06280869 1.41931076
 1.12135734 0.49204617 0.38531584]
39
[0.91482936 0.78250049 0.78782903 0.75430501 0.62583812 0.54837423