In [16]:
import numpy as np
a = np.array([0.9, 0.9, 0.9 ])
print(np.ones(6).shape)

data = a.reshape((1, ) + a.shape)
print(data.shape)

(6,)
(1, 3)


In [8]:
print((-1, )+ (6, ) )

(-1, 6)


In [3]:
a = np.array([0.9, 0.9 ])
actions = np.array([10, 20])
print(a*actions.max(dim=1))

NameError: name 'np' is not defined

In [6]:
print(f"madezhishiang {a}, pingweismbuneg{a.shape}")

madezhishiang [0.9 0.9], pingweismbuneg(2,)


In [18]:
aa = 34523.32425
print(f'floating point formatted: {aa:2.4f}', end='*')
print('\n')
print("Art: %10d, Price per Unit:%8.2f" %(444, 543.6254), end='*')

floating point formatted: 34523.3242*

Art:        444, Price per Unit: 543.63*

In [7]:
import torch
x = torch.tensor([1.4, 6.8], requires_grad=True)
a = torch.tensor([0.4, 0.6], requires_grad=True)

F = a*x 
F.backward(gradient=torch.ones_like(F))  
# 代表F是个tensor,我要对一个多维方程进行求导,指定我的y的维度
F_scale = torch.multiply(a, x)


print(f"打印对a的导数: {a.grad}")
# 结果就是[1.4, 6.8] 但是实际上是 [ dF/da1 = (dF1/da1 + dF2/da1), dF/da2 = (dF1/da2 + dF2/da2)
print(F_scale)
loss = torch.nn.functional.mse_loss(x, a)  # 因为是mse, 所以就是一个标量
print(loss)


打印对a的导数: tensor([1.4000, 6.8000])
tensor([0.5600, 4.0800], grad_fn=<MulBackward0>)
tensor(19.7200, grad_fn=<MseLossBackward0>)


In [17]:
r = torch.randn([3,], requires_grad=True)  # 代表其他值对这个值的导数要被保留
x = torch.tensor([1., 2., 3.], requires_grad=True)
t = torch.tensor([11., 11., 11.], requires_grad=True)
F = r*x + t*x  # 三维向量
F.backward(gradient=torch.ones_like(F))   # backward代表这个F就是最终的loss, 从这个loss开始向后生成computational graphic, 一直计算到requires_grad的参数上.

print(r.grad)
print(x.grad) 

tensor([1., 2., 3.])
tensor([10.9222, 12.1767,  9.8881])


In [11]:
import torch
mean = torch.arange(10., 20., requires_grad=True)
var = torch.arange(0., 1., 0.1 , requires_grad=True)
# values = torch.normal(mean, var)
def normal_pdf(x, mean, var):
    pdf = 1 / torch.sqrt(2 * torch.pi * var) * torch.exp(-1/2 * (x - mean)**2 / var)
    return pdf
pi = normal_pdf(torch.randn(10, 1), mean, var)
print(pi.prod(dim=1))
# values.backward(gradient=torch.ones_like(values))
# print(mean.grad)
# print(var.grad)

tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       grad_fn=<ProdBackward1>)


In [14]:
mean = torch.tensor([2.54, 1.23])
var = torch.tensor([0.35, 3.02])
def normal_pdf(x, mean, var):
    pdf = 1 / torch.sqrt(2 * torch.pi * var) * torch.exp(-1/2 * (x - mean)**2 / var)
    return pdf

pi = normal_pdf(torch.tensor([1.2, 3.8]), mean, var)
print(pi)



tensor([0.0519, 0.0769])


In [23]:
ran = np.random.rand(32,32,3)
print(ran[0][0])
ran2 = np.random.rand(3, 32, 32)
print(ran2[:, 31, 31])


[0.60242776 0.32515096 0.47935122]
[0.50994032 0.56574342 0.51175941]


In [24]:
ran = np.random.rand(32,32,3)
fl = ran.flatten()
print(fl.shape)

(3072,)


In [31]:
a = torch.tensor([1, 2, 3, 4, 5])
ra = reversed(a)
print(ra)
print(a)

tensor([5, 4, 3, 2, 1])
tensor([1, 2, 3, 4, 5])


In [29]:
g = [1, 2, 3, 4, 5]
new = g[::-1]
print(new)
print(g)

[5, 4, 3, 2, 1]
[1, 2, 3, 4, 5]


In [13]:
import torch
ran = torch.randn([32, 3])

max_value, idx = torch.max(ran, 0)
print(max_value)
print(idx)
print(ran.prod(dim=1).shape)

tensor([1.9921, 2.2195, 2.2799])
tensor([14, 20,  0])
torch.Size([32])


In [2]:
import torch
ran = torch.randn([32, 3])
print(ran[-5, :])

tensor([-1.7179,  1.1552,  0.9148])
